# this is the same of IntentMessage.msg (todo: how to emebed here the same message instead of duplicate fields?)
# this is not really used anymore
string context_id
string original_input
string intent_name
float32 confidence
string[] pay_load
---
bool success
