string context_id
string text
bool canbeenqued # if set true, it will added to the execution queue,otherwise discarded
bool canbediscarded # if set true, and another session is on going, this will drop the previous session
string[] intents
---
bool success
string context_id # return the context assigned to this id (the same of input if present or an automatic generated)